export OPTEE_QEMU_DIR="/opt/optee-qemu"
export CROSS_COMPILE="$OPTEE_QEMU_DIR/toolchains/aarch64/bin/aarch64-linux-gnu-"
export HOST_CROSS_COMPILE="$OPTEE_QEMU_DIR/toolchains/aarch64/bin/aarch64-linux-gnu-"
export TEEC_EXPORT="$OPTEE_QEMU_DIR/optee_client/out/export/usr"
export TA_DEV_KIT_DIR="$OPTEE_QEMU_DIR/optee_os/out/arm/export-ta_arm64"
